server:
  port: 7003

spring:
  application:
    name: client-feign

eureka:
  client:
    service-url:
      defaultZone: http://localhost:6060/eureka
    fetch-registry: true #不从注册中心拉取注册表

feign:
  hystrix:
    enabled: true  #开启Feign的熔断功能
  client:
    config:
      default:
        connectTimeout: 12000
        readTimeout: 12000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 10000